// <auto-generated />
using System;
using EntrenamientoFuerza.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EntrenamientoFuerza.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260924180246_InicialEsquema")]
    partial class InicialEsquema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EntrenamientoFuerza.Models.Ejercicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("video_url");

                    b.HasKey("Id");

                    b.ToTable("ejercicios", (string)null);
                });

            modelBuilder.Entity("EntrenamientoFuerza.Models.Rutina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activa");

                    b.Property<int>("CreadoPorId")
                        .HasColumnType("integer")
                        .HasColumnName("creado_por_id");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("CreadoPorId");

                    b.ToTable("rutinas", (string)null);
                });

            modelBuilder.Entity("EntrenamientoFuerza.Models.RutinaEjercicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DescansoSegundos")
                        .HasColumnType("integer")
                        .HasColumnName("descanso_segundos");

                    b.Property<int?>("DuracionSegundos")
                        .HasColumnType("integer")
                        .HasColumnName("duracion_segundos");

                    b.Property<int>("EjercicioId")
                        .HasColumnType("integer")
                        .HasColumnName("ejercicio_id");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<int?>("Repeticiones")
                        .HasColumnType("integer")
                        .HasColumnName("repeticiones");

                    b.Property<int>("RutinaId")
                        .HasColumnType("integer")
                        .HasColumnName("rutina_id");

                    b.Property<int>("Series")
                        .HasColumnType("integer")
                        .HasColumnName("series");

                    b.HasKey("Id");

                    b.HasIndex("EjercicioId");

                    b.HasIndex("RutinaId");

                    b.ToTable("rutina_ejercicios", (string)null);
                });

            modelBuilder.Entity("EntrenamientoFuerza.Models.SesionDiario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Notas")
                        .HasColumnType("text")
                        .HasColumnName("notas");

                    b.Property<int?>("RutinaId")
                        .HasColumnType("integer")
                        .HasColumnName("rutina_id");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("RutinaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("sesiones_diario", (string)null);
                });

            modelBuilder.Entity("EntrenamientoFuerza.Models.SesionEjercicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EjercicioId")
                        .HasColumnType("integer")
                        .HasColumnName("ejercicio_id");

                    b.Property<string>("Notas")
                        .HasColumnType("text")
                        .HasColumnName("notas");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<int>("SesionDiarioId")
                        .HasColumnType("integer")
                        .HasColumnName("sesion_diario_id");

                    b.HasKey("Id");

                    b.HasIndex("EjercicioId");

                    b.HasIndex("SesionDiarioId");

                    b.ToTable("sesion_ejercicios", (string)null);
                });

            modelBuilder.Entity("EntrenamientoFuerza.Models.SesionSerie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Completada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("completada");

                    b.Property<int?>("DuracionSegundosReal")
                        .HasColumnType("integer")
                        .HasColumnName("duracion_segundos_real");

                    b.Property<int>("NumeroSerie")
                        .HasColumnType("integer")
                        .HasColumnName("numero_serie");

                    b.Property<decimal?>("PesoKg")
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("peso_kg");

                    b.Property<int?>("RepeticionesRealizadas")
                        .HasColumnType("integer")
                        .HasColumnName("repeticiones_realizadas");

                    b.Property<int>("SesionEjercicioId")
                        .HasColumnType("integer")
                        .HasColumnName("sesion_ejercicio_id");

                    b.HasKey("Id");

                    b.HasIndex("SesionEjercicioId");

                    b.ToTable("sesion_series", (string)null);
                });

            modelBuilder.Entity("EntrenamientoFuerza.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateTime>("FechaAlta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_alta")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre_usuario");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("rol");

                    b.HasKey("Id");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("EntrenamientoFuerza.Models.Rutina", b =>
                {
                    b.HasOne("EntrenamientoFuerza.Models.Usuario", "CreadoPor")
                        .WithMany("Rutinas")
                        .HasForeignKey("CreadoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreadoPor");
                });

            modelBuilder.Entity("EntrenamientoFuerza.Models.RutinaEjercicio", b =>
                {
                    b.HasOne("EntrenamientoFuerza.Models.Ejercicio", "Ejercicio")
                        .WithMany("RutinaEjercicios")
                        .HasForeignKey("EjercicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EntrenamientoFuerza.Models.Rutina", "Rutina")
                        .WithMany("RutinaEjercicios")
                        .HasForeignKey("RutinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ejercicio");

                    b.Navigation("Rutina");
                });

            modelBuilder.Entity("EntrenamientoFuerza.Models.SesionDiario", b =>
                {
                    b.HasOne("EntrenamientoFuerza.Models.Rutina", "Rutina")
                        .WithMany("Sesiones")
                        .HasForeignKey("RutinaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EntrenamientoFuerza.Models.Usuario", "Usuario")
                        .WithMany("Sesiones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rutina");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EntrenamientoFuerza.Models.SesionEjercicio", b =>
                {
                    b.HasOne("EntrenamientoFuerza.Models.Ejercicio", "Ejercicio")
                        .WithMany("SesionEjercicios")
                        .HasForeignKey("EjercicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EntrenamientoFuerza.Models.SesionDiario", "SesionDiario")
                        .WithMany("SesionEjercicios")
                        .HasForeignKey("SesionDiarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ejercicio");

                    b.Navigation("SesionDiario");
                });

            modelBuilder.Entity("EntrenamientoFuerza.Models.SesionSerie", b =>
                {
                    b.HasOne("EntrenamientoFuerza.Models.SesionEjercicio", "SesionEjercicio")
                        .WithMany("Series")
                        .HasForeignKey("SesionEjercicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SesionEjercicio");
                });

            modelBuilder.Entity("EntrenamientoFuerza.Models.Ejercicio", b =>
                {
                    b.Navigation("RutinaEjercicios");

                    b.Navigation("SesionEjercicios");
                });

            modelBuilder.Entity("EntrenamientoFuerza.Models.Rutina", b =>
                {
                    b.Navigation("RutinaEjercicios");

                    b.Navigation("Sesiones");
                });

            modelBuilder.Entity("EntrenamientoFuerza.Models.SesionDiario", b =>
                {
                    b.Navigation("SesionEjercicios");
                });

            modelBuilder.Entity("EntrenamientoFuerza.Models.SesionEjercicio", b =>
                {
                    b.Navigation("Series");
                });

            modelBuilder.Entity("EntrenamientoFuerza.Models.Usuario", b =>
                {
                    b.Navigation("Rutinas");

                    b.Navigation("Sesiones");
                });
#pragma warning restore 612, 618
        }
    }
}
